import {
  Award,
  Banknote,
  Bell,
  Boxes,
  Briefcase,
  Building2,
  CalendarDays,
  CreditCard,
  FileText,
  Flag,
  FolderKanban,
  Gauge,
  GraduationCap,
  Home,
  IdCard,
  KeyRound,
  LayoutDashboard,
  LibraryBig,
  type LucideIcon,
  Receipt,
  Repeat,
  RotateCcw,
  Route,
  Settings,
  ShieldCheck,
  Sparkles,
  Store,
  Ticket,
  Users,
  Wallet,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  home: Home,
  library: LibraryBig,
  projects: FolderKanban,
  programs: Route,
  live: CalendarDays,
  community: Users,
  career: Award,
  orders: Receipt,
  notifications: Bell,
  billing: CreditCard,
  overview: LayoutDashboard,
  gauge: Gauge,
  courses: GraduationCap,
  cohorts: CalendarDays,
  coupons: Ticket,
  earnings: Wallet,
  members: Users,
  storefront: Store,
  settings: Settings,
  mentor: ShieldCheck,
  reviews: FileText,
  defenses: Sparkles,
  profile: IdCard,
  tenants: Building2,
  moderation: ShieldCheck,
  refunds: RotateCcw,
  payouts: Banknote,
  flags: Flag,
  licenses: Boxes,
  sso: KeyRound,
  roster: IdCard,
  reports: FileText,
  jobs: Briefcase,
  switch: Repeat,
  admin: ShieldCheck,
  org: Building2,
  studio: Store,
};

export function NavIcon({
  name,
  className,
}: {
  name: string;
  className?: string;
}) {
  const Icon = ICONS[name] ?? Home;
  return <Icon className={className} />;
}
